PR de docs/#54 - diagrama-de-classes
UnBArqDsw2022-2/2022.2_G4_IDotPet pull request #70
Opened 2022-11-28 21:49 UTC by PedroLucasCM

#54 - Criação do documento de Diagrama de Classe e criação da pasta modelagem + move do DDD para a pasta

2022-11-28 23:16 UTC, klyssmannoliveira requested changes
Pessoal, para uma primeira versão está ok. Mas acho que conseguimos acrescentar mais classes aí, podemos ter as classes: "anuncio", "mensagem", "denuncia"... com isso podemos explorar os conceitos de agregação, herança e composição. Olhem essa referência aqui como inspiração: http://wiki.foz.ifpr.edu.br/wiki/index.php/Lucky_Pets
Precisamos de uma versão final para a apresentação.

2022-11-29 01:07 UTC, Nicolas-Roberto commented
Acho que ta bom pra primeira versão, podia adicionar um campo que fala se o animal é de rua ou não, acho que isso importa pro usuário

2022-11-29 01:19 UTC, PedroLucasCM commented
Mudanças feitas, classes adicionadas, etc.
Sobre o ser encontrado de rua também acho uma ideia legal mas pode ser feita pela descrição.
Qualquer coisa se os desenvolvedores quiserem colocar nós mudamos.

2022-11-29 23:07 UTC, victordscabral approved these changes
PR aceito.

2022-11-29 23:12 UTC, Nicolas-Roberto commented
A imagem do diagrama de classes ta com o link quebrado

2022-11-29 23:23 UTC, merged